### ISSUE TITLE
jUnitReport.xml contains wrong data with smart sharding

### ISSUE THREAD

**Issue by andreschab90** [Flank/flank#618] opened 2019-11-13 15:25 UTC
I am using smart sharding and i recognized the the jUnitReport-xml file contains wrong data compared to real results of the matrixes. I can provide you some xml files for debugging if needed

**Comment by bootstraponline** [comment] 2019-11-13 16:34
I'll need more info to identity, reproduce, and resolve the issue.

**Comment by andreschab90** [comment] 2019-11-13 17:04
i had  a look in the links to inside the junit file. 
I have a test A which fails, but the junit reports successful, because the link for this test-case points to the wrong matrix, to a successful one

**Comment by bootstraponline** [comment] 2019-11-15 23:22
Thanks! I'll take a look soon.

**Comment by bootstraponline** [comment] 2019-11-17 20:17
Debugged. Root cause is FTL does not produce XML files for all failed matrices. Flank currently detects failures by parsing the XML. If a failed matrix doesn't produce an XML then they'll be missing from the Flank XML report.

Moving to API based results fetching may solve the issue.
https://github.com/TestArmada/flank/issues/545

**Closed** 2020-03-24 09:36 UTC
