### ISSUE TITLE
Unit Tests failing on IT github action -- ubuntu runner

### ISSUE THREAD

**Issue by pawelpasterz** [Flank/flank#1891] opened 2021-05-03 20:15 UTC
IT task is failing on ubuntu (only) https://github.com/Flank/flank/runs/2494446534?check_suite_focus=true#step:6:139

The error seems to be related to `MockServer` not starting correctly (or too late?)

https://github.com/Flank/flank/blob/master/test_runner/src/main/kotlin/ftl/mock/MockServer.kt#L386
https://github.com/Flank/flank/blob/master/test_runner/src/main/kotlin/ftl/args/ArgsHelper.kt#L185

Scope:
* investigate the problem
* try to figure out why it's happening only on ubuntu (20.04) -- that knowledge may help us understand future problems with ubuntu
* fix
* as fallback solution, downgrading ubuntu to 18.04 should do the job (to verify)

**Comment by pawelpasterz** [comment] 2021-05-24 12:18
[to verify] Is it still valid?

**Comment by Sloox** [comment] 2021-06-01 12:18
After updates done on previous tickets I am not seeing the same behavior. 
This can be reopened if it occurs again. But cannot reproduce it two separate local ubuntu installations.
20-04 & 21-01.
It may have been fixed in this merge: https://github.com/Flank/flank/pull/1942

**Closed by Sloox** 2021-06-01 12:18 UTC
Labels: Bug, Tiger 🐯
