### ISSUE TITLE
Shards failed - no test cases inside

### ISSUE THREAD

**Issue by bootstraponline** [Flank/flank#818] opened 2020-05-27 16:04 UTC
> Mr.uno 
>
> One or more shards failed because there are no test cases inside. Please check your sharding configuration. I've encountered this a couple times with our submodule tests which use a lot of additional test apks. Maybe some error somewhere in that logic - I've only ever seen it with the submodule tests. This is from the latest Flank version.

![image](https://user-images.githubusercontent.com/1173057/83044337-e4f21e80-9ff8-11ea-908a-b742f0431ab8.png)

https://firebase-community.slack.com/archives/C72V6UW8M/p1590537597298100

**Comment by inktomi** [comment] 2020-05-27 16:25
Thank you for getting this filed for me! I'm not feeling well today, but I wanted to provide our config as well. 

We build a dummy app for the `app` - it's basically just the app you get from the "New Application" template in Android Studio. 

```yaml
flank:
  additional-app-test-apks:
  - test: feature/1/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/2/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/3/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/4/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/5/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/6/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/7/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/8/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/9/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/10/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/11/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/12/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/13/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/14/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/15/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/16/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/17/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/18/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/19/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/20/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/21/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/22/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/23/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/24/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/25/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/26/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  - test: feature/27/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  legacy-junit-result: 'false'
  local-result-dir: sub-modules-flank-results
  max-test-shards: 5
  project: project-id-12345
  run-timeout: 20m
  smart-flank-gcs-path: gs://project-id-12345-flank/submodules-timing.xml
gcloud:
  app: ./sample-app/build/outputs/apk/debug/sample-app-tester-debug.apk
  async: false
  auto-google-login: false
  device:
  - model: NexusLowRes
    version: 23
  environment-variables:
    clearPackageData: true
  performance-metrics: false
  record-video: false
  results-bucket: sub-modules-flank-results
  test: feature/28/build/outputs/apk/androidTest/debug/android-debug-androidTest.apk
  test-targets:
  - notAnnotation org.junit.Ignore
  use-orchestrator: true
```

I was getting an error like this before I added the `notAnnotation` to ensure that Ignored tests were not causing issues. After I added that, it seemed like maybe a bucket consisted entirely of ignored tests or something like that and I started getting the error in the original report here about a shard having no tests. I only noticed ` One or more shards failed because there are no test cases inside. Please check your sharding configuration.` in the Firebase UI after adding the test filter but the error seemed to happen in both cases since the stacktrace is consistent. 

```
 java.lang.ClassNotFoundException: Invalid name: no tests found
at java.lang.Class.classForName(Native Method)
at java.lang.Class.forName(Class.java:324)
at androidx.test.internal.runner.TestLoader.doCreateRunner(TestLoader.java:72)
at androidx.test.internal.runner.TestLoader.getRunnersFor(TestLoader.java:104)
at androidx.test.internal.runner.TestRequestBuilder.build(TestRequestBuilder.java:793)
at androidx.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:547)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:390)
at com.americanexpress.android.test.view.ViewTestRunner.onStart(ViewTestRunner.kt:25)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1879) 
```

**Comment by bootstraponline** [comment] 2020-05-27 16:29
Thank you for the detailed information. I've added this to the top of our ranked column. It'll be worked on by the team soon.

You can install https://www.zenhub.com/extension if you'd like to see the ZenHub board on the GitHub issues page. 🙂

**Comment by jan-gogo** [comment] 2020-05-27 22:12
I wonder that required fix is already implemented [here](https://github.com/Flank/flank/pull/817/files#diff-a9c528f3980c0aea4f4c7b47ba86894cR41) and is waiting for code review. This implementation [filters out](https://github.com/Flank/flank/pull/817/files#diff-38c994008147b09c478da6f6d71f586dR48) empty shards and [drops](https://github.com/Flank/flank/pull/817/files#diff-38c994008147b09c478da6f6d71f586dR61) apks without shards. So no empty shards and no apks without shards should be passed to execution.

**Comment by inktomi** [comment] 2020-05-27 22:14
I’m happy to build flank off that branch and give it a try. I can probably do that tomorrow.

**Comment by inktomi** [comment] 2020-05-28 16:54
I built flank off the `android-test-context` branch using `./gradlew clean assembleShadowDist` and still see the issue. 

For example, `matrix-29sueztfa3twi` reports 5 shards for me. Overall it's failed. Each shard is shown as red in the Firebase UI. Firebase is *not* showing the warning in the original report about the shards failing because of no test cases, however as you can see, the shard seemed to fail because of no test cases. 

Overall matrix.. 
<img width="1081" alt="Screen Shot 2020-05-28 at 9 52 01 AM" src="https://user-images.githubusercontent.com/74583/83170210-0a4e5d80-a0c9-11ea-8011-08513ad281d8.png">

Clicking into the first shard
<img width="1300" alt="Screen Shot 2020-05-28 at 9 52 09 AM" src="https://user-images.githubusercontent.com/74583/83170254-1b976a00-a0c9-11ea-8b7b-d689e9c086c1.png">

Details on the `null` failure
<img width="1024" alt="Screen Shot 2020-05-28 at 9 52 15 AM" src="https://user-images.githubusercontent.com/74583/83170280-25b96880-a0c9-11ea-8296-12d7c9ad28cf.png">

**Comment by inktomi** [comment] 2020-05-28 17:27
Here's a heavily redacted shards output to help. If you need more specific information, I can work to get that for you. 

[android_shards.json.zip](https://github.com/Flank/flank/files/4697280/android_shards.json.zip)

**Comment by inktomi** [comment] 2020-06-01 15:27
This was improperly closed by #817 @bootstraponline @jan-gogo. The issue reproduced for me on that branch.

**Comment by bootstraponline** [comment] 2020-06-02 03:00
@inktomi thanks for catching this!

**Comment by technoir42** [comment] 2020-06-03 15:48
We have the same issue. In total there are ~200 instrumented tests but we have a custom annotation-based and execute only 10% of them at a time. If number of shards > 2, there is a high chance that one of the shards will have no tests and will fail the whole matrix.
Another, related problem is that tests are not evenly distributed among shards after filtering. Is this something that can be improved on Flank side?

**Comment by bootstraponline** [comment] 2020-06-03 18:24
Thanks for this feedback. I have raised this with the team.

**Comment by jan-gogo** [comment] 2020-06-04 14:02
@inktomi @technoir42 Are you use `test-targets-always-run` and `additional-apks` in your  config? The answer may help resolve this problem.

**Comment by technoir42** [comment] 2020-06-04 14:53
We don't use either of them:
```
fladle {
    serviceAccountCredentials = file("pathToCredentials")
    useOrchestrator = true
    environmentVariables = [
        "clearPackageData"     : "true"
    ]
    timeoutMin = 30
    recordVideo = true
    performanceMetrics = false
    devices = [
        ["model": "Pixel2", "version": "27", "orientation": "portrait", "locale": "en"]
    ]
    projectId = "id"
    flankVersion = "20.05.2"
    testShards = 5
    flakyTestAttempts = 0
}
```

**Comment by pawelpasterz** [comment] 2020-06-04 15:18
@technoir42 
Do your test apks have the same name?

**Comment by inktomi** [comment] 2020-06-04 15:37
In our run, we use `additional-apks` but not `test-targets-always-run` - you can see our config up a bit in this issue. Our test apks are all named uniquely after the feature module they're built from. Each has a unique path and name. 

In the config above I renamed the files just to keep the feature names private.

**Comment by pawelpasterz** [comment] 2020-06-05 04:09
> In our run, we use `additional-apks` but not `test-targets-always-run` - you can see our config up a bit in this issue. Our test apks are all named uniquely after the feature module they're built from. Each has a unique path and name.
> 
> In the config above I renamed the files just to keep the feature names private.

Flank has both options `additional-apks`[1] and `additional-app-test-apks`[2]. I can see only [2] in config you posted. Just wanted to be sure we are on the same page :)

**Comment by inktomi** [comment] 2020-06-05 14:39
Sorry, you're right. Apologies.

**Comment by bootstraponline** [comment] 2020-06-13 04:33
Some additional context from Slack: https://firebase-community.slack.com/archives/C1MTSQ5QT/p1591032162198200

Firebase Test Lab considers any shard with all skipped/ignored tests to be failed. I think that's a design defect in FTL and the team is considering making this behavior configurable. In the meantime, Flank should add some intelligence to ensure test shards contain only tests that we expect to run.

**Comment by pawelpasterz** [comment] 2020-06-13 14:07
> Firebase Test Lab considers any shard with all skipped/ignored tests to be failed. I think that's a design defect in FTL and the team is considering making this behavior configurable. In the meantime, Flank should add some intelligence to ensure test shards contain only tests that we expect to run.

Flank had such feature before -- skip all `@Ignore` tests. But there was a feature request to attach those to test run.
Also, I don't think it's the case here since ignored tests looks like this in FTL matrix :
<img width="1320" alt="Screenshot 2020-06-13 at 15 54 59" src="https://user-images.githubusercontent.com/32893017/84570507-49013a80-ad8e-11ea-8608-6dbe9a582aa8.png">
but here we have different outcome 
https://user-images.githubusercontent.com/74583/83170254-1b976a00-a0c9-11ea-8b7b-d689e9c086c1.png

**Comment by pawelpasterz** [comment] 2020-06-13 14:28
> Flank should add some intelligence to ensure test shards contain only tests that we expect to run.
On the second thought, I think we could add warning, throw an error and terminate run (or make it configurable) in case when one shard would consists of ignored tests only, WDYT?

**Comment by bootstraponline** [comment] 2020-06-13 17:27
> On the second thought, I think we could add warning, throw an error and terminate run (or make it configurable) in case when one shard would consists of ignored tests only, WDYT?

As flank specifies exactly which tests to run on FTL via test targets, I think we should filter out ignored tests before sending them to FTL. 

I think the broader issue is Flank currently lacks an end to end test to simulate this large multi-module use case and detect bugs. We should probably invest in this area to be more proactive about finding problems both in FLank and FTL itself.

**Comment by inktomi** [comment] 2020-06-13 18:01
I agree, I think it would be best for flank to filter tests that are marked `@Ignore`. Maybe to future proof that, `@Ignore` would be the default, but make it configurable somehow. I know some teams use different annotations for flaky tests vs disabled tests etc.

**Comment by pawelpasterz** [comment] 2020-06-13 18:31
@bootstraponline @inktomi 
Got your point. What I am trying to say is, behavior you both are describing was implemented at very beginning of flank. There was #629 feature request to change it and include ignored tests. IMHO original behavior (filtering ingored) was better. 
I just want explicitly point that it's kind of regression and decide if we are ok with that.

Changing this behavior will be easy so it's all matter of decision. 


> I think the broader issue is Flank currently lacks an end to end test to simulate this large multi-module use case and detect bugs. We should probably invest in this area to be more proactive about finding problems both in Flank and FTL itself.

Yes, please! I would love to have some time (without new features) to implement it with the team

**Comment by bootstraponline** [comment] 2020-06-13 18:43
> What I am trying to say is, behavior you both are describing was implemented at very beginning of flank. There was #629 feature request to change it and include ignored tests. That time the only way to achieve it was to include `@Ignore` tests in matrix. (maybe there is another way now? )

I think there's some missing context, Firebase use to consider ignored tests as passing so there was no cost for Flank to send ignored tests to a matrix. At some point Firebase decided to treat ignored tests as failing when they make up an entire matrix. In general when Firebase changes behavior then Flank often has to follow as they control the logic for matrix outcomes.

If I understand the request in https://github.com/Flank/flank/issues/629, the user wants @Ignore tests represented in the XML. Maybe we could do the following:

- Filter all @Ignore / skipped / etc. tests before sending them to FTL
- Keep track in Flank of all the Ignored tests
- FTL runs the matrix, and at the end Flank adds in the @Ignored tests to the XML report

What do you think?

> Yes, please! I would love to have some time (without new features) to implement it with the team

Awesome. Yeah I think we should pause all the new feature work until we invest more in quality.

**Comment by pawelpasterz** [comment] 2020-06-13 19:06
> I think there's some missing context, Firebase use to consider ignored tests as passing so there was no cost for Flank to send ignored tests. At some point Firebase decided to treat ignored tests as failing when they make up an entire shard. In general when Firebase changes behavior then Flank often has to follow as they control the logic for matrix outcomes.

👍 I was thinking the same as well

> If I understand the request in #629, the user wants @Ignore tests represented in the XML. Maybe we could do the following:

Filter all @Ignore / skipped / etc. tests before sending them to FTL
Keep track in Flank of all the Ignored tests
FTL runs the matrix, and at the end Flank adds in the @Ignore tests to the final merged XML report
What do you think?

Agreed, with current flank (after refactor and with our better understanding of flank and FTL) we should be able to achieve it. But still, I am not sure if this should be resolved within this issue, I believe ignored tests are not root cause. But I might be wrong of course. @inktomi do you have some ignored tests within your apk? Is it possible for you to verify if there was shard with only ignored tests inside?

**Comment by bootstraponline** [comment] 2020-06-13 19:17
> I believe ignored tests are not root cause

Agreed.

**Comment by pawelpasterz** [comment] 2020-06-18 10:58
@inktomi @technoir42  
We were not able to reproduce this error with the info you provided us (and believe me, we tried dozens of times :) ) but we tracked down few issues that might be potential root cause and fixed it with #853 and #858. Fixes are already merged and available in snapshot version https://github.com/Flank/flank/releases/tag/flank_snapshot. We tested solutions according to our best knowledge of your case but still can't be 100% sure that 'this is it'.

It will be extremely helpful if you could help us and verify if the issue still occurs with snapshot version. 
Also, please check https://github.com/Flank/flank/pull/855/files and let us know if you could provide us any information that is missing there.

cc
@bootstraponline

**Comment by bootstraponline** [comment] 2020-06-18 16:39
@inktomi Please retest with [Flank v20.06.2](https://github.com/Flank/flank/releases/tag/v20.06.2), then provide matrix ids for the shards that fail so we can investigate the root cause.

**Comment by bootstraponline** [comment] 2020-06-23 06:12
I talked with `Mr.uno` on Slack today. Updating to the latest Flank and AndroidX libraries seems to have fixed the problem. Amex was on v1.1.0, however firebase is using orchestrator v1.2.0. My current theory is that this error is related to having an out of date AndroidX library and using sharding with orchestrator.

- https://firebase-community.slack.com/archives/C1MTSQ5QT/p1592526170398200?thread_ts=1592498669.392500&cid=C1MTSQ5QT
- https://github.com/android/android-test/issues/264
- https://github.com/android/android-test/releases/tag/androidx-test-1.3.0-rc01
- https://github.com/Flank/flank/releases/tag/v20.06.2

**Comment by jan-gogo** [comment] 2020-06-25 14:27
> Updating to the latest Flank and AndroidX libraries seems to have fixed the problem

@bootstraponline So, do you think, can we close this issue?

**Comment by bootstraponline** [comment] 2020-06-26 04:43
> @bootstraponline So, do you think, can we close this issue?

I think we can close the issue after updating the documentation. Something like, if you see the error "One or more shards failed because there are no test cases inside." then update Flank and all the AndroidX libs to the latest version.

**Comment by inktomi** [comment] 2020-07-03 21:58
I agree, after doing that on our project the error seemed to go away. I used the latest Test Orchestrator, 1.3x

**Closed** 2020-07-10 12:39 UTC
Labels: Bug

**Comment by adecker89** [comment] 2020-10-30 16:58
I've started seeing this issue with
Flank: v20.09.3
Test Orchestrator: 1.3.0
AndroidX Test: 1.3.0

adding `notAnnotation org.junit.Ignore` works as a workaround.

**Comment by bootstraponline** [comment] 2020-10-30 18:04
@adecker89 can you raise this on the FTL Slack and post a matrix id? The root cause is FTL does not allow users to specify that no tests should be a successful run instead of a failure.

**Comment by adecker89** [comment] 2020-11-04 14:23
Thanks, I've done so.

As an update, I actually think that in my case this error was due to sending a `@RequiresDevice` annotated test to an emulator and not actually related to `@Ignore`. I will most likely be able to explicitly filter out that annotation since I'm only targeting emulators in this particular device matrix, but I could see it being troublesome if I needed to target both devices and emulators together.

**Comment by damianw** [comment] 2021-06-29 17:02
We're seeing this issue as well, usually because we have `@SdkSuppress` on on a test which happens to be the only test on the shard.

Although in our case, FTL doesn't detect that there were no tests in the shard - instead, it reports a single test with the name `null` as seen here:

![image](https://user-images.githubusercontent.com/2455337/123837954-46518480-d8c0-11eb-8849-2497baaca2d6.png)
![image](https://user-images.githubusercontent.com/2455337/123837987-510c1980-d8c0-11eb-81b1-d06da99aad79.png)

```
java.lang.ClassNotFoundException: Invalid name: no tests found
at java.lang.Class.classForName(Native Method)
at java.lang.Class.forName(Class.java:400)
at androidx.test.internal.runner.TestLoader.doCreateRunner(TestLoader.java:72)
at androidx.test.internal.runner.TestLoader.getRunnersFor(TestLoader.java:105)
at androidx.test.internal.runner.TestRequestBuilder.build(TestRequestBuilder.java:804)
at androidx.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:575)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:393)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1932)
```

We also don't see the message that you mentioned in the output, "One or more shards failed because there are no test cases inside." The table in the output just says that "N tests failed".

@bootstraponline Would this be considered the same issue, or should I file a different one? Or is this something that needs to be looked into on the FTL side? (Or even ATO?) Is this something that can be solved in Flank?

**Comment by pawelpasterz** [comment] 2021-06-30 06:48
@damianw I think it is due to the fact that flank does not correctly handle `@SdkSuppress` annotation. Based on your input I think flank should be updated with some logic to skip tests when SDK version requirement is not fulfilled.

Thanks for reporting this issue!

**Comment by pawelpasterz** [comment] 2021-06-30 06:53
@damianw @bootstraponline https://github.com/Flank/flank/issues/2053

**Comment by damianw** [comment] 2021-06-30 18:24
Alright, thanks! Will follow that issue.
