### ISSUE TITLE
Confirm Flank prints status for flaky test attempts

### ISSUE THREAD

**Issue by bootstraponline** [Flank/flank#738] opened 2020-04-24 20:23 UTC
Issue is happening on Flank snapshot

> Flank is assuming that a matrix contains only a single execution for each device, which used to be true, but is not true when --flaky-test-attempts is used.

```
9m  1s matrix-1nwh2yd26l923 Pixel2-29 FINISHED
17m 23s matrix-1nwh2yd26l923 FINISHED

```

The last device sent a finished at 9mins, but the test took 17 mins to end. Any idea what’s taking all that time?

> 
> @bootstraponline @Sridhar Vadlamani This matrix is specifying --flaky-test-attempts=2, and some of the initial test executions within the matrix had failed tests, and so were rerun again after they initially failed. This process adds new test executions to the test matrix many minutes after the matrix is first created.
> Just a hunch, not confirmed, but I suspect the problem here is that Flank assumes the number of test executions is static during the life of the matrix and doesn't report any status for the additional reruns?
> 
> pauldavis  17 minutes ago
> Either that or Flank is assuming that a matrix contains only a single execution for each device, which used to be true, but is not true when --flaky-test-attempts is used.

Let's confirm that Flank is printing intermediate status when the flaky-test-attempts flag is used.

**Comment by bootstraponline** [comment] 2020-04-25 00:13
https://github.com/Flank/flank/blob/b9596bc83027a5bc94bb5d1dca9a8adb81dcea5a/test_runner/src/main/kotlin/ftl/run/model/RunningDevices.kt#L67-L68

Pau mentioned it might be related to this map. Matrices now contain multiple executions per device. Flank originally wasn't built to support this.

**Comment by pawelpasterz** [comment] 2020-04-25 19:29
I think those three issues (#738 , #717 , #681 ) may have common root cause which is moving to server side sharding (but can differ in details). Prior, every shard was separate matrix and flank had detailed info about every shard(matrix). Now, within one matrix we can have up to 50 shards and we've lost some info about progress. 
https://cloud.google.com/sdk/gcloud/reference/beta/firebase/test/android/run#--num-flaky-test-attempts 
If `--num-flaky-test-attempts=2` two additional shards are created and executed in parallel. Since flank has `old way` of printing progress (matrix level) it is not aware of additional (re-run) shards. From flank's perspective matrix is still running and that leads to 'time jumps' and lack of information.

We definitely need to implement a way to print progress on shard level and (imo) most of logging problems will be solved. 

Let me know what you think, thanks!

**Closed** 2020-05-18 15:58 UTC
